from collections import Counter
from functools import reduce

magnetic_poetry_sets = \
{
	"Riccardo & Yuko": "Riccardo Riccardo Gherardi Gherardi Yuko Yuko Hara Hara kaba kaba chan chan san san",
	"Original": "& & a a a a a a about above ache ad after all am am an an and and and and apparatus are are arm as as as as ask at at at away bare be beat beauty bed beneath bitter black blood blow blue boil boy breast but but but but butt by by can chant chocolate cool could crush cry d day death delirious diamond did do do dream dress drive drool drunk eat ed ed ed ed egg elaborate enormous er es est fast feet fiddle finger fluff for forest frantic friend from from garden girl go goddess gorgeous gown hair has have have he he head heave her her here him his his honey hot how I I I I if in in in ing ing ing ing ing ing is is is is is it it it juice lake language languid lather lazy less let lick lie life light like like like live love luscious lust ly ly ly ly mad man me me me mean meat men milk mist moan moon mother music must my my my need never no no not not of of of of on on one or our over pant peach petal picture pink play please pole pound puppy purple put r r rain raw recall red repulsive rip rock rose run rust s s s s s s s s s s s sad said sausage say scream sea see shadow she she shine ship shot show sing sit skin sky sleep smear smell smooth so soar some sordid spray spring still stop storm suit summer sun sweat sweet swim symphony the the the the the their there these they those though thousand through time tiny to to to together tongue trudge TV ugly up urge us use want want was watch water wax we we were what when whisper who why will wind with with woman worship y y y y yet you you you you",
	"Geek": "& a a a about access action alien almost always am an and and are as ask at avatar awesome battle be bit boost bot brain but by byte can cheat cook cloud code come complete computer content could crash create d digital do download dragon droid dungeon e each easy ed ed empire er est every evil figure file fire flame for force fortress from game geek get giga girl galactic good hack hard hard drive has have he head her him his how hub humanoid I I if in information ing ing intelligent interface is is it joy lap light like like line linear live love ly make me meme microwave nachos more must my name native need net network never not of of off on online open or our out password performance perl phaser planet play program protect put r rule s s screen server set sexy share she sinister smart so soft some source space speed squadron star stick stream stun system tech than that the the then there they this this though through to to too top trek tube up upgrade upload utility video virus want war ware was we web were which while wifi will with with world would write y you you your",
	"Love": "& a a a a a all always am an an and and and and angel another are are are arm as as ask at at at away be be been believe belong beside best better between big bloom blue boy bread brother but but by by can care charm cheer child chocolate come compare could d d dance day devote dew did do do dream drink each eat ed ed emotion enjoy er er es est evening ever every eye faith family fascinate father favorite feel felt fight fill find flower for for friend ful full fun gentle get gift girl give glad go god goddess good grow guy had hand happy has have he he he heart help her here hero him his his hold home honor hope hour hug I I I I if in in ing ing ing innocent is is it it join joy keep kind know language laugh let life life lift light like like listen little live look love love luck ly ly make make man me me me mind moment morning mother music must mutual my my my near need neighbor never nice night no not of of off old on on one only open or our out over peace pink play please positive power promise protect quiet r receive regard remember respect rhapsody river run s s s s s sacred sad say search see share she she she sister sit sky smile so soar soft some song soul sound spirit star strong sun sweet take tear tell than thank that the the the the the their them then there they thing think this though thousand through time time tiny to to to together touch true trust two under universe up us use voice want want warm was we we we were when where which will wing wish with with woman word work world y y you you you you your",
	"Nature": "& & a a a about above after air al almost always am an an ancient and and animal are as as ask at at be beautiful bee behold beneath berry between bird blanket bloom blossom blue bough breathe breeze bright brown bucolic but but by can climb cloud cold color come could cover cycle d d daffodil dark dawn deep did do do dusk e earth eat ed eden er es est every fall feel fertile flower follow for forest fresh from frost fruit full garden gentle give grass green grow happy harmony has have he her here him his hot how I I if in in ing ing insect intuition is is it know lake leave let lichen life light like like listen live lonely long love ly ly make me moist moon more moss mountain murmur must my my nature never night no of of off on only or our out over path peace poetry prairie pure quiet r rain relax rest river rock root rose rustle s s sacred said sanctuary say season secret see seed shade she shine so soft some song soon soul spirit spring squirrel stone stroll summer sun sweet tendril than that the the then there they thick thing this though thrive through to to too tree trunk up use verdant vine vivid walk wander warm was watch water we were wet when which who why wild wild will wind winter with wither world would y y you you",
	"Poet": "& & & & a a a a a a a about after air all almost always am an an and and and and angel are are as as ask at at away baby be belly bleed blue blush born boy breath breeze brilliant bring broken brother bug but but but by cake can candy caramel cat celebrate champagne child cloud coffee color come concrete cool corduroy could crap cup d d dance dark day dazzle decay delicious desire devour did die dirt do do dog drink e e eat ed ed ed embrace er er es es eternity explore eye fat father ferocious fever fire fish flower fly fool for for for from from ghost girl give glass go go god good grass green growl hard has haunt have he he heal heart her her here him his hole home hot how I I I I I ice if in in in ing ing ing ing ing ing is is is is is it it it it joy kiss laugh less let lie life like like like linger lip liquid listen live long look ly ly magic make man marble may me me melt men moist more morning must my my naked need never night no no not not o ocean of of of of old on on one only open or our out over peace perfume picture pie poetry poison porcelain prisoner put r r red remember rhythm s s s s s s s s sacred sad said sail salt secret see self sex she she sister sky slow smile smoke so soft some son star steam steel surround than that the the the the their them then there they thing this this those though throb time to to to to tree two universe up use vast velvet voice wake warm was we we were wet when which who wild will window with with woman women word work would y y y yet you you you young",
	"Moustache": "'stache 'Vette a a a about alluring almost always am an an and and are at athletic attitude baby bar believe bey big bushy but by call can chest chick cologne comb come confident convertible cool cop could cruise d delicious dig do don't drive dude ed ed equipped er es est every face facial fashion fast for freedom from fun fuzzy get go good great groovy grow guy hair hairy handle hard has have he hello her him his hot how I I I'm if impressive in ing ing intrigue is is it Jesus know lady let's life lifestyle like like lip live look love lover ly make man man's masculine me men moist more mouth Mr. muscle must mustache mustache my mystery need ness never no not ode of of off on one operator or our out party people player poet power pretty put r ready ride right rockin' rule s s s say score sensuous sex shave she smile smoke smooth some special style suit symbol take than that the the then there they thing this though through time to to too t-shirt up upper van very vibes want was wax we well were which while will wine with with world y y you you your"
}

for name, words in magnetic_poetry_sets.items():
	magnetic_poetry_sets[name] = Counter(magnetic_poetry_sets[name].split())

merged = reduce(lambda x, y: x | y, [s for n, s in magnetic_poetry_sets.items() if n is not "Original"])
full = magnetic_poetry_sets['Original'] + merged
words = sorted(full.elements())

print('Total words: {}'.format(len(words)))
print('  '.join(words))
